package classwork.Exception;

import java.util.Scanner;

public class ExceptionConcept {
    public static void main(String[] args) throws InterruptedException, IndexOutOfBoundsException {
//        String[] names=new String[5];
//        System.out.println("Please Enter 5 Persons Name !!");
//        for (int i = 0; i <= 5; i++) {
//            if (i >= 5)
//                throw new IndexOutOfBoundsException("Index is greater than size.");
//            names[i] = new Scanner(System.in).nextLine();
//        }

        //        try{
//            System.out.println(10/0);
//        } catch(ArithmeticException e){
//            System.out.println("Not divisible by 0");
//        }
//        System.out.println("Start");
//        Thread.sleep(5000);
//        System.out.println("End");

//        try {
//            throw new CustomException();
//        } catch(CustomException e)
//        {
//            System.out.printf("Catching a custom exception!");
//            //e.getMessage(); prints system error message
//        }

        // \u000d System.out.println("sgsg");
        // \u000d //is a newline character
    }
}
